"""Generate selection-criteria.md for operator audit trail."""

from __future__ import annotations

from typing import Any

from .contacts import summarize_pool


def render_selection_criteria(
    *,
    source_file: str,
    format_name: str,
    pool_summary: dict[str, int],
    selection_meta: dict[str, Any],
    selected_count: int,
) -> str:
    seed = selection_meta.get("seed")
    seed_line = f"Reproducibility seed: `{seed}`" if seed is not None else "Reproducibility seed: none (strict rank order)"
    return f"""# Canary-25 selection criteria

**Purpose:** G1 Loop Proof Card — Row 4 (25 hand-approved supervised sends, 7-day tracking).  
**Generated by:** `cato canary select`  
**Source file:** `{source_file}`  
**Detected format:** `{format_name}`

---

## Pool summary (after validation)

| Metric | Count |
|--------|------:|
| Valid rows imported | {pool_summary.get('total', 0)} |
| tier_a | {pool_summary.get('tier_a', 0)} |
| tier_b | {pool_summary.get('tier_b', 0)} |
| tier_c | {pool_summary.get('tier_c', 0)} |
| tier unknown | {pool_summary.get('tier_unknown', 0)} |
| Unique domains in pool | {selection_meta.get('pool_unique_domains', 0)} |

---

## Selection rules (v1.0)

1. **Validation:** require `domain` + deliverable `receiver_email`; skip forbidden domains (`conduitscore.com`, `www.conduitscore.com`).
2. **Dedupe:** one contact per domain (keep best-ranked row for that domain).
3. **Rank order:** `tier_a` → `tier_b` → `tier_c` → unknown; then lower `send_priority` number first; then higher `score` from notes; then domain A–Z.
4. **Batch size:** first **{selected_count}** rows after ranking{'' if seed is None else ' (with seeded shuffle within tier bands)'}.
5. **Supervision:** every send is **hand-approved** by operator — Cato does **not** auto-send until G1 is signed on `docs/loop-proof-card.md`.

{seed_line}

---

## Row 4 pass criteria (operator records in manifest / tracking sheet)

| Metric | Target |
|--------|--------|
| Sends completed | 25 / 25 |
| Replies **or** audit views | ≥ 1 |
| Complaint rate | < 0.1% of sends |
| Bounce rate | recorded (document in tracking sheet) |
| Tracking window | 7 days from first send |

---

## Commands

```text
cato canary import --source <csv>          # validate pool, no writes
cato canary select --source <csv>          # write manifest + this file + tracking-sheet.csv
cato canary mark-sent --contact <id>       # after each approved send
cato canary record --contact <id> --reply  # --contact required; also --audit-view, --complaint, --bounce
cato canary sync-tracking                  # merge tracking-sheet.csv edits into manifest
cato canary status                         # Row 4 pass/fail summary
```

---

## Safety (G1 gates unchanged)

- `gates.g1_manual_loop_proven` must stay **false** until rows 1–6 are PASS on the loop proof card.
- `live_outreach_allowed` remains **false** — use dry-run / manual sends only for this canary.
"""
